

export const INCREMENT_COUNTER = "INCREMENT_COUNTER"

export const DECREMENT_COUNTER = "DECREMENT_COUNTER"

export const GET_MEDICINES = "GET_MEDICINES"


export const DELETE_MEDICINES = "DELETE_MEDICINES"

export const GET_DEPARTMENT = "GET_DEPARTMENT"



