

export const INCREMENT_COUNTER = "INCREMENT_COUNTER"

export const DECREMENT_COUNTER = "DECREMENT_COUNTER"

export const GET_MEDICINES = "GET_MEDICINES"


export const DELETE_MEDICINES = "DELETE_MEDICINES"
export const ADD_MEDICINES = "ADD_MEDICINES"
export const UPDATE_MEDICINES = "UPDATE_MEDICINES"

export const LODING_MEDICINES = "LODING_MEDICINES"
